import Image from "next/image";

export default function Skills() {
  return (
    <div className="my-10">
      {/* <h1 className="text-center text-5xl font-light my-8">Skills</h1> */}
      <div className="w-full inline-flex flex-nowrap overflow-hidden my-8">
        <ul className="animate-infinite-scroll flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll">
          <li>
            <Image
              width={40}
              height={40}
              src="/Images/Icons/react.png"
              alt="React"
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/html.png"
              alt="html"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/css.png"
              alt="css"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image src="/Images/Icons/js.png" alt="js" width={40} height={40} />
          </li>
          <li>
            <Image
              src="/Images/Icons/node.svg"
              alt="node"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/redux.svg"
              alt="redux"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/express.svg"
              alt="express"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/tailwind.svg"
              alt="tailwind"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/postgresql.svg"
              alt="postgresql"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/next.svg"
              alt="next"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/sql.svg"
              alt="sql"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/prisma.svg"
              alt="prisma"
              width={40}
              height={40}
            />
          </li>
        </ul>
        <ul className="animate-infinite-scroll flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll">
          <li>
            <Image
              width={40}
              height={40}
              src="/Images/Icons/react.png"
              alt="React"
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/html.png"
              alt="html"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/css.png"
              alt="css"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image src="/Images/Icons/js.png" alt="js" width={40} height={40} />
          </li>
          <li>
            <Image
              src="/Images/Icons/node.svg"
              alt="node"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/redux.svg"
              alt="redux"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/express.svg"
              alt="express"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/tailwind.svg"
              alt="tailwind"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/postgresql.svg"
              alt="postgresql"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/next.svg"
              alt="next"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/sql.svg"
              alt="sql"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/prisma.svg"
              alt="prisma"
              width={40}
              height={40}
            />
          </li>
        </ul>{" "}
        <ul className="animate-infinite-scroll flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll">
          <li>
            <Image
              width={40}
              height={40}
              src="/Images/Icons/react.png"
              alt="React"
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/html.png"
              alt="html"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/css.png"
              alt="css"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image src="/Images/Icons/js.png" alt="js" width={40} height={40} />
          </li>
          <li>
            <Image
              src="/Images/Icons/node.svg"
              alt="node"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/redux.svg"
              alt="redux"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/express.svg"
              alt="express"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/tailwind.svg"
              alt="tailwind"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/postgresql.svg"
              alt="postgresql"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/next.svg"
              alt="next"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/sql.svg"
              alt="sql"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/prisma.svg"
              alt="prisma"
              width={40}
              height={40}
            />
          </li>
        </ul>{" "}
        <ul className="animate-infinite-scroll flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll">
          <li>
            <Image
              width={40}
              height={40}
              src="/Images/Icons/react.png"
              alt="React"
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/html.png"
              alt="html"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/css.png"
              alt="css"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image src="/Images/Icons/js.png" alt="js" width={40} height={40} />
          </li>
          <li>
            <Image
              src="/Images/Icons/node.svg"
              alt="node"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/redux.svg"
              alt="redux"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/express.svg"
              alt="express"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/tailwind.svg"
              alt="tailwind"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/postgresql.svg"
              alt="postgresql"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/next.svg"
              alt="next"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/sql.svg"
              alt="sql"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/prisma.svg"
              alt="prisma"
              width={40}
              height={40}
            />
          </li>
        </ul>{" "}
        <ul className="animate-infinite-scroll flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll">
          <li>
            <Image
              width={40}
              height={40}
              src="/Images/Icons/react.png"
              alt="React"
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/html.png"
              alt="html"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/css.png"
              alt="css"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image src="/Images/Icons/js.png" alt="js" width={40} height={40} />
          </li>
          <li>
            <Image
              src="/Images/Icons/node.svg"
              alt="node"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/redux.svg"
              alt="redux"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/express.svg"
              alt="express"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/tailwind.svg"
              alt="tailwind"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/postgresql.svg"
              alt="postgresql"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/next.svg"
              alt="next"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/sql.svg"
              alt="sql"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/prisma.svg"
              alt="prisma"
              width={40}
              height={40}
            />
          </li>
        </ul>{" "}
        <ul className="animate-infinite-scroll flex items-center justify-center md:justify-start [&_li]:mx-8 [&_img]:max-w-none animate-infinite-scroll">
          <li>
            <Image
              width={40}
              height={40}
              src="/Images/Icons/react.png"
              alt="React"
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/html.png"
              alt="html"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/css.png"
              alt="css"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image src="/Images/Icons/js.png" alt="js" width={40} height={40} />
          </li>
          <li>
            <Image
              src="/Images/Icons/node.svg"
              alt="node"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/redux.svg"
              alt="redux"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/express.svg"
              alt="express"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/tailwind.svg"
              alt="tailwind"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/postgresql.svg"
              alt="postgresql"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/next.svg"
              alt="next"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/sql.svg"
              alt="sql"
              width={40}
              height={40}
            />
          </li>
          <li>
            <Image
              src="/Images/Icons/prisma.svg"
              alt="prisma"
              width={40}
              height={40}
            />
          </li>
        </ul>
      </div>
    </div>
  );
}
